-- Insert 20 countries with real images from Unsplash
INSERT INTO countries (
  country_name,
  country_code,
  continent,
  img_url,
  banner_img_url,
  flag_emoji,
  description,
  short_description,
  popular,
  featured_order,
  active,
  slug,
  currency_code,
  language,
  best_time_to_visit,
  timezone,
  visa_requirements
) VALUES
  (
    'France',
    'FR',
    'Europe',
    'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&q=80',
    'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=1200&q=80',
    '🇫🇷',
    'France captivates with its iconic landmarks, world-renowned cuisine, exquisite wines, and rich cultural heritage. From the romantic streets of Paris to the sun-soaked beaches of the French Riviera, and the lavender fields of Provence to the historic châteaux of the Loire Valley, France offers endless enchantment.',
    'Experience art, culture, and world-class cuisine in the heart of Europe',
    true,
    1,
    true,
    'france',
    'EUR',
    'French',
    'April to October',
    'Europe/Paris',
    'Visa-free for EU citizens; Schengen visa for others'
  ),
  (
    'Japan',
    'JP',
    'Asia',
    'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&q=80',
    'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&q=80',
    '🇯🇵',
    'Japan seamlessly blends ancient traditions with cutting-edge technology. Discover serene temples, witness the beauty of cherry blossoms, indulge in exquisite cuisine, experience the efficiency of bullet trains, and immerse yourself in a culture that honors both its past and future.',
    'Where ancient traditions meet modern innovation',
    true,
    2,
    true,
    'japan',
    'JPY',
    'Japanese',
    'March to May, September to November',
    'Asia/Tokyo',
    'Visa-free for many countries (up to 90 days); e-visa available'
  ),
  (
    'Italy',
    'IT',
    'Europe',
    'https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?w=800&q=80',
    'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=1200&q=80',
    '🇮🇹',
    'Italy is a treasure trove of art, history, and culinary excellence. Explore ancient Roman ruins, Renaissance masterpieces, picturesque coastal villages, rolling Tuscan vineyards, and savor authentic pasta, pizza, gelato, and espresso in their birthplace.',
    'Explore timeless history, art, and culinary perfection',
    true,
    3,
    true,
    'italy',
    'EUR',
    'Italian',
    'April to June, September to October',
    'Europe/Rome',
    'Visa-free for EU citizens; Schengen visa for others'
  ),
  (
    'Spain',
    'ES',
    'Europe',
    'https://images.unsplash.com/photo-1543783207-ec64e4d95325?w=800&q=80',
    'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=1200&q=80',
    '🇪🇸',
    'Spain pulses with vibrant energy, from flamenco dancing and bullfighting to world-class art museums and architectural wonders by Gaudí. Experience sun-drenched beaches, lively tapas bars, historic Moorish palaces, and the passionate spirit of Spanish culture.',
    'Feel the passion of culture and stunning Mediterranean landscapes',
    true,
    4,
    true,
    'spain',
    'EUR',
    'Spanish',
    'April to June, September to October',
    'Europe/Madrid',
    'Visa-free for EU citizens; Schengen visa for others'
  ),
  (
    'Greece',
    'GR',
    'Europe',
    'https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?w=800&q=80',
    'https://images.unsplash.com/photo-1503152394-c571994fd383?w=1200&q=80',
    '🇬🇷',
    'Greece is the cradle of Western civilization, home to ancient ruins, whitewashed island villages, crystal-clear waters, and warm hospitality. Walk in the footsteps of philosophers, explore mythological sites, and indulge in Mediterranean cuisine under endless blue skies.',
    'Journey through ancient mythology and paradise islands',
    true,
    5,
    true,
    'greece',
    'EUR',
    'Greek',
    'April to June, September to October',
    'Europe/Athens',
    'Visa-free for EU citizens; Schengen visa for others'
  ),
  (
    'Thailand',
    'TH',
    'Asia',
    'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=800&q=80',
    'https://images.unsplash.com/photo-1528181304800-259b08848526?w=1200&q=80',
    '🇹🇭',
    'Thailand enchants visitors with its golden temples, tropical beaches, bustling markets, and legendary street food. Experience the vibrant energy of Bangkok, the serenity of northern mountains, the beauty of island paradises, and the warmth of Thai smiles.',
    'Experience tropical paradise and vibrant cultural traditions',
    true,
    6,
    true,
    'thailand',
    'THB',
    'Thai',
    'November to February',
    'Asia/Bangkok',
    'Visa-free for many countries (15-30 days); visa on arrival available'
  ),
  (
    'United Kingdom',
    'GB',
    'Europe',
    'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800&q=80',
    'https://images.unsplash.com/photo-1486299267070-83823f5448dd?w=1200&q=80',
    '🇬🇧',
    'The United Kingdom offers a captivating blend of royal heritage, literary history, iconic landmarks, and diverse landscapes. Explore historic castles, world-class museums, charming villages, and vibrant cities while experiencing British culture, afternoon tea, and traditional pubs.',
    'Uncover centuries of history and royal heritage',
    true,
    7,
    true,
    'united-kingdom',
    'GBP',
    'English',
    'May to September',
    'Europe/London',
    'Visa-free for many countries (up to 6 months); visa required for some'
  ),
  (
    'United States',
    'US',
    'North America',
    'https://images.unsplash.com/photo-1485738422979-f5c462d49f74?w=800&q=80',
    'https://images.unsplash.com/photo-1501466044931-62695aada8e9?w=1200&q=80',
    '🇺🇸',
    'The United States offers incredible diversity, from cosmopolitan cities and entertainment capitals to natural wonders like the Grand Canyon and Yellowstone. Experience American innovation, cultural melting pots, national parks, iconic road trips, and the spirit of opportunity.',
    'Explore vast landscapes and endless possibilities coast to coast',
    true,
    8,
    true,
    'united-states',
    'USD',
    'English',
    'Year-round (varies by region)',
    'America/New_York',
    'ESTA or visa required for most international visitors'
  ),
  (
    'Australia',
    'AU',
    'Oceania',
    'https://images.unsplash.com/photo-1523482580672-f109ba8cb9be?w=800&q=80',
    'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=1200&q=80',
    '🇦🇺',
    'Australia captivates with its unique wildlife, stunning beaches, ancient Aboriginal culture, and adventurous spirit. Discover the Great Barrier Reef, explore the Outback, experience world-class cities, and encounter kangaroos, koalas, and landscapes found nowhere else on Earth.',
    'Discover unique wildlife and breathtaking natural wonders',
    true,
    9,
    true,
    'australia',
    'AUD',
    'English',
    'September to November, March to May',
    'Australia/Sydney',
    'ETA or eVisitor visa required for most visitors'
  ),
  (
    'Iceland',
    'IS',
    'Europe',
    'https://images.unsplash.com/photo-1504893524553-b855bce32c67?w=800&q=80',
    'https://images.unsplash.com/photo-1531168556467-80aace0d0144?w=1200&q=80',
    '🇮🇸',
    'Iceland is a land of fire and ice, where volcanic landscapes meet massive glaciers. Witness the Northern Lights, bathe in geothermal hot springs, explore ice caves, chase waterfalls, and experience the raw, dramatic beauty of this Nordic island nation.',
    'Witness dramatic landscapes and spectacular natural phenomena',
    true,
    10,
    true,
    'iceland',
    'ISK',
    'Icelandic, English',
    'June to August (midnight sun), September to March (Northern Lights)',
    'Atlantic/Reykjavik',
    'Visa-free for EU/EEA citizens; Schengen visa for others'
  ),
  (
    'Portugal',
    'PT',
    'Europe',
    'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800&q=80',
    'https://images.unsplash.com/photo-1548707309-dcebeab8a270?w=1200&q=80',
    '🇵🇹',
    'Portugal charms visitors with its colorful tiles, Port wine, stunning coastline, and warm hospitality. Explore historic Lisbon, discover Porto''s riverside beauty, relax on Algarve beaches, and experience a rich maritime heritage and delicious seafood cuisine.',
    'Discover coastal beauty, rich history, and authentic charm',
    false,
    null,
    true,
    'portugal',
    'EUR',
    'Portuguese',
    'March to May, September to October',
    'Europe/Lisbon',
    'Visa-free for EU citizens; Schengen visa for others'
  ),
  (
    'Morocco',
    'MA',
    'Africa',
    'https://images.unsplash.com/photo-1489749798305-4fea3ae63d43?w=800&q=80',
    'https://images.unsplash.com/photo-1597212618440-806262de4f6b?w=1200&q=80',
    '🇲🇦',
    'Morocco is an exotic blend of ancient medinas, Sahara Desert adventures, Atlas Mountains, and Atlantic coastline. Experience vibrant souks, stunning riads, traditional hammams, aromatic spices, and the welcoming spirit of North African culture.',
    'Experience the magic of ancient medinas and Saharan adventures',
    false,
    null,
    true,
    'morocco',
    'MAD',
    'Arabic, French',
    'March to May, September to November',
    'Africa/Casablanca',
    'Visa-free for many countries (up to 90 days)'
  ),
  (
    'New Zealand',
    'NZ',
    'Oceania',
    'https://images.unsplash.com/photo-1507699622108-4be3abd695ad?w=800&q=80',
    'https://images.unsplash.com/photo-1469521669194-babb45599def?w=1200&q=80',
    '🇳🇿',
    'New Zealand offers breathtaking landscapes made famous by "The Lord of the Rings" films. Experience dramatic fjords, snow-capped mountains, pristine beaches, geothermal wonders, adventure sports, and Māori culture in this unspoiled paradise.',
    'Adventure through Middle-earth and pristine natural beauty',
    false,
    null,
    true,
    'new-zealand',
    'NZD',
    'English, Māori',
    'December to February, March to May',
    'Pacific/Auckland',
    'eTA or visa required; visa-free for some countries'
  ),
  (
    'Brazil',
    'BR',
    'South America',
    'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=800&q=80',
    'https://images.unsplash.com/photo-1516306580123-e6e52b1b7b5f?w=1200&q=80',
    '🇧🇷',
    'Brazil pulsates with energy, from Carnival celebrations and samba rhythms to the Amazon rainforest and stunning beaches. Experience the iconic Christ the Redeemer, Copacabana Beach, diverse ecosystems, and the passionate, welcoming Brazilian spirit.',
    'Feel the rhythm of samba and explore natural wonders',
    false,
    null,
    true,
    'brazil',
    'BRL',
    'Portuguese',
    'December to March (summer), September to November',
    'America/Sao_Paulo',
    'Visa-free for many countries; e-visa available for some'
  ),
  (
    'Switzerland',
    'CH',
    'Europe',
    'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?w=800&q=80',
    'https://images.unsplash.com/photo-1527668752968-14dc70a27c95?w=1200&q=80',
    '🇨🇭',
    'Switzerland is synonymous with pristine Alpine beauty, precision watches, delicious chocolate, and efficient trains. Explore charming villages, world-class ski resorts, crystal-clear lakes, and experience Swiss perfection in every detail.',
    'Experience Alpine perfection and timeless Swiss quality',
    false,
    null,
    true,
    'switzerland',
    'CHF',
    'German, French, Italian, Romansh',
    'June to September (hiking), December to March (skiing)',
    'Europe/Zurich',
    'Visa-free for EU citizens; Schengen visa for others'
  ),
  (
    'Turkey',
    'TR',
    'Europe/Asia',
    'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=800&q=80',
    'https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?w=1200&q=80',
    '🇹🇷',
    'Turkey bridges two continents, offering a fascinating blend of Eastern and Western cultures. Discover ancient ruins, stunning mosques, unique hot air balloon rides over Cappadocia, bustling bazaars, and delicious Turkish cuisine.',
    'Where East meets West in spectacular fashion',
    false,
    null,
    true,
    'turkey',
    'TRY',
    'Turkish',
    'April to May, September to October',
    'Europe/Istanbul',
    'E-visa available online for most countries'
  ),
  (
    'Egypt',
    'EG',
    'Africa',
    'https://images.unsplash.com/photo-1539768942893-daf53e448371?w=800&q=80',
    'https://images.unsplash.com/photo-1572252009286-268acec5ca0a?w=1200&q=80',
    '🇪🇬',
    'Egypt is home to one of the world''s oldest civilizations. Marvel at the Pyramids of Giza, cruise the Nile River, explore ancient temples, discover pharaonic treasures, and immerse yourself in 5,000 years of captivating history.',
    'Uncover 5,000 years of ancient civilization and mystery',
    false,
    null,
    true,
    'egypt',
    'EGP',
    'Arabic',
    'October to April',
    'Africa/Cairo',
    'Visa on arrival or e-visa available for most countries'
  ),
  (
    'Canada',
    'CA',
    'North America',
    'https://images.unsplash.com/photo-1503614472-8c93d56e92ce?w=800&q=80',
    'https://images.unsplash.com/photo-1517935706615-2717063c2225?w=1200&q=80',
    '🇨🇦',
    'Canada offers vast wilderness, cosmopolitan cities, and friendly locals. Experience the Rocky Mountains, Niagara Falls, vibrant Toronto and Vancouver, French-Canadian culture in Quebec, and pristine natural beauty that stretches from coast to coast.',
    'Explore vast wilderness and multicultural cities',
    false,
    null,
    true,
    'canada',
    'CAD',
    'English, French',
    'June to September',
    'America/Toronto',
    'eTA or visa required depending on nationality'
  ),
  (
    'Vietnam',
    'VN',
    'Asia',
    'https://images.unsplash.com/photo-1528127269322-539801943592?w=800&q=80',
    'https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=1200&q=80',
    '🇻🇳',
    'Vietnam captivates with its stunning natural beauty, rich history, delicious cuisine, and welcoming people. Explore bustling Hanoi, cruise Ha Long Bay, discover ancient Hoi An, experience vibrant Ho Chi Minh City, and savor authentic pho and banh mi.',
    'Discover rich culture, stunning landscapes, and amazing cuisine',
    false,
    null,
    true,
    'vietnam',
    'VND',
    'Vietnamese',
    'February to April, August to October',
    'Asia/Ho_Chi_Minh',
    'E-visa or visa on arrival available for most countries'
  ),
  (
    'Peru',
    'PE',
    'South America',
    'https://images.unsplash.com/photo-1526392060635-9d6019884377?w=800&q=80',
    'https://images.unsplash.com/photo-1587595431973-160d0d94add1?w=1200&q=80',
    '🇵🇪',
    'Peru is home to Machu Picchu, one of the world''s most iconic archaeological sites. Explore Incan ruins, the Amazon rainforest, colorful Andean culture, Lake Titicaca, and savor world-renowned Peruvian cuisine in this land of ancient mysteries.',
    'Trek to Machu Picchu and explore ancient Incan civilization',
    false,
    null,
    true,
    'peru',
    'PEN',
    'Spanish, Quechua',
    'April to October (dry season)',
    'America/Lima',
    'Visa-free for most countries (up to 90-183 days)'
  )
ON CONFLICT (country_code) DO NOTHING;