-- Insert 10 activities with React Icons icon names
INSERT INTO activities (
  name,
  slug,
  category,
  icon_name,
  emoji,
  image_url,
  short_description,
  description,
  popular,
  featured_order,
  difficulty_levels,
  season_availability,
  fitness_level,
  min_age,
  color_hex
) VALUES
  (
    'Skiing',
    'skiing',
    'Winter Sports',
    'FaSkiing', -- React Icons: Font Awesome
    '⛷️',
    'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=800&q=80',
    'Hit the slopes in world-class ski resorts',
    'Experience the thrill of skiing down pristine mountain slopes. Whether you''re a beginner or expert, discover perfect powder, stunning alpine views, and après-ski culture.',
    true,
    1,
    ARRAY['beginner', 'intermediate', 'advanced', 'expert'],
    ARRAY['winter'],
    'moderate',
    8,
    '#4A90E2'
  ),
  (
    'Scuba Diving',
    'scuba-diving',
    'Water Sports',
    'GiScubaTanks', -- React Icons: Game Icons
    '🤿',
    'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&q=80',
    'Explore underwater worlds and marine life',
    'Dive into crystal-clear waters and discover vibrant coral reefs, exotic marine life, and underwater caves. Perfect for certified divers and beginners alike.',
    true,
    2,
    ARRAY['beginner', 'intermediate', 'advanced'],
    ARRAY['spring', 'summer', 'fall'],
    'moderate',
    12,
    '#0EA5E9'
  ),
  (
    'Hiking',
    'hiking',
    'Adventure',
    'GiHiking', -- React Icons: Game Icons
    '🥾',
    'https://images.unsplash.com/photo-1551632811-561732d1e306?w=800&q=80',
    'Trek through stunning natural landscapes',
    'Embark on scenic hiking trails through mountains, forests, and valleys. From leisurely day hikes to challenging multi-day treks, connect with nature.',
    true,
    3,
    ARRAY['beginner', 'intermediate', 'advanced', 'expert'],
    ARRAY['spring', 'summer', 'fall'],
    'moderate',
    6,
    '#10B981'
  ),
  (
    'Wildlife Safari',
    'wildlife-safari',
    'Wildlife',
    'GiBinoculars', -- React Icons: Game Icons
    '🦁',
    'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800&q=80',
    'Encounter magnificent wildlife in natural habitats',
    'Witness Africa''s Big Five, rare species, and incredible wildlife in their natural environment. Expert guides ensure unforgettable encounters.',
    true,
    4,
    ARRAY['beginner', 'intermediate'],
    ARRAY['year-round'],
    'low',
    5,
    '#F59E0B'
  ),
  (
    'Cultural Tours',
    'cultural-tours',
    'Cultural',
    'FaLandmark', -- React Icons: Font Awesome
    '🏛️',
    'https://images.unsplash.com/photo-1533928298208-27ff66555d8d?w=800&q=80',
    'Immerse yourself in local culture and traditions',
    'Explore ancient temples, historic sites, local markets, and traditional ceremonies. Learn about rich cultural heritage from knowledgeable guides.',
    true,
    5,
    ARRAY['beginner'],
    ARRAY['year-round'],
    'low',
    0,
    '#8B5CF6'
  ),
  (
    'Snorkeling',
    'snorkeling',
    'Water Sports',
    'GiDivingDagger', -- React Icons: Game Icons (closest to snorkel)
    '🤽',
    'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80',
    'Discover colorful marine life just below the surface',
    'Float over stunning coral reefs and swim alongside tropical fish. Perfect for all ages and skill levels, no certification required.',
    true,
    6,
    ARRAY['beginner', 'intermediate'],
    ARRAY['spring', 'summer', 'fall', 'year-round'],
    'low',
    6,
    '#06B6D4'
  ),
  (
    'Mountain Biking',
    'mountain-biking',
    'Adventure',
    'FaBiking', -- React Icons: Font Awesome
    '🚵',
    'https://images.unsplash.com/photo-1544191696-102dbdaeeaa0?w=800&q=80',
    'Ride thrilling trails through mountains and forests',
    'Navigate challenging terrain, technical descents, and scenic routes. From smooth forest paths to adrenaline-pumping downhill tracks.',
    true,
    7,
    ARRAY['intermediate', 'advanced', 'expert'],
    ARRAY['spring', 'summer', 'fall'],
    'high',
    12,
    '#EF4444'
  ),
  (
    'Wine Tasting',
    'wine-tasting',
    'Culinary',
    'FaWineGlassAlt', -- React Icons: Font Awesome
    '🍷',
    'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800&q=80',
    'Sample world-class wines in beautiful vineyards',
    'Tour prestigious wineries, learn about wine-making, and taste exceptional vintages in stunning vineyard settings with expert sommeliers.',
    true,
    8,
    ARRAY['beginner'],
    ARRAY['spring', 'summer', 'fall'],
    'low',
    18,
    '#DC2626'
  ),
  (
    'Kayaking',
    'kayaking',
    'Water Sports',
    'GiKayak', -- React Icons: Game Icons
    '🛶',
    'https://images.unsplash.com/photo-1473448912268-2022ce9509d8?w=800&q=80',
    'Paddle through pristine waters and coastlines',
    'Glide through calm lakes, river rapids, or coastal waters. Explore hidden coves, observe wildlife, and enjoy peaceful water adventures.',
    false,
    null,
    ARRAY['beginner', 'intermediate', 'advanced'],
    ARRAY['spring', 'summer', 'fall'],
    'moderate',
    10,
    '#14B8A6'
  ),
  (
    'Rock Climbing',
    'rock-climbing',
    'Adventure',
    'GiMountainClimbing', -- React Icons: Game Icons
    '🧗',
    'https://images.unsplash.com/photo-1522163182402-834f871fd851?w=800&q=80',
    'Scale dramatic cliffs and rock faces',
    'Challenge yourself on natural rock formations or via ferratas. Experienced guides ensure safety while you conquer stunning vertical terrain.',
    false,
    null,
    ARRAY['intermediate', 'advanced', 'expert'],
    ARRAY['spring', 'summer', 'fall'],
    'high',
    14,
    '#F97316'
  )
ON CONFLICT (slug) DO NOTHING;